spring.application.name=java-learn-ecom

app.name=Java Learn E-Commerce
app.version=0.0.1

spring.datasource.url=jdbc:postgresql://localhost:55432/java_learn_ecom
spring.datasource.username=user_java_learn_ecom
spring.datasource.password=v@nnguyen123

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true